tbtadm: check sysfs device file for thunderbolt device first.
intel/thunderbolt-software-user-space pull request #55
Opened 2018-03-14 16:15 UTC by nirmoy

Exception like below doesnt looks nice, catch early

Exception: boost::filesystem::directory_iterator::construct: No such file or directory: "/sys/bus/thunderbolt/devices"

2018-03-14 19:32 UTC, ybernat requested changes
Thanks for this!
The error handling definitely needs to be improved and this is an important step towards it.
Just a few minor code-style comments.

2018-03-14 19:32 UTC, ybernat commented on tbtadm/controller.cpp
> +bool tbtadm::Controller::sysfsDeviceExists()
No need to make this a member function.
It can be added to the anonymous namespace like the other helpers we have in this file (line 240).

2018-03-14 19:32 UTC, ybernat commented on tbtadm/controller.cpp
> +        return 0;
`false`

2018-03-14 19:32 UTC, ybernat commented on tbtadm/controller.cpp
> +    return 1;
`true`

2018-03-15 10:11 UTC, nirmoy commented
@ybernat Thanks for you comment, please review again.

2018-03-23 10:58 UTC, finikorg requested changes
Otherwise LGTM

2018-03-23 10:58 UTC, finikorg commented on tbtadm/controller.cpp
> +
@ybernat I saw some code without braces for single statements, but other code has them, I personally like Linux kernel way more (then we need to convert other code to this style).

2018-03-23 10:58 UTC, finikorg commented on tbtadm/controller.cpp
> +        return;
approveAll() should call approveAll(const fs::path& dir), so this is not needed here

2018-03-26 09:22 UTC, nirmoy commented
@finikorg @ybernat please review again.

2018-03-26 20:57 UTC, ybernat approved these changes

2018-03-26 20:58 UTC, ybernat commented
@finikorg 
Anything else or we can merge this?

2018-03-27 07:27 UTC, finikorg approved these changes
LGTM, although I would not print error message in helper, and print it instead in the caller, this would allow us to use helper in some more places.

2018-03-27 09:13 UTC, merged